<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search courses_q</name>
   <tag></tag>
<<<<<<< Updated upstream
   <elementGuidId>06b67f95-bfa1-4116-9596-eadcc476735d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchinput-61dea30e4119b61dea30e32da15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='region-main']/div/div/div/form/div/input</value>
=======
   <elementGuidId>a671ebc4-e99b-4b19-8935-edb4c7ea0944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchinput-61dee35cbd4b861dee35cb52f62</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchinput-61dee35cbd4b861dee35cb52f62']</value>
>>>>>>> Stashed changes
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
<<<<<<< Updated upstream
      <value>searchinput-61dea30e4119b61dea30e32da15</value>
=======
      <value>searchinput-61dee35cbd4b861dee35cb52f62</value>
>>>>>>> Stashed changes
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search courses</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search courses</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-region</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
<<<<<<< Updated upstream
      <value>id(&quot;searchinput-61dea30e4119b61dea30e32da15&quot;)</value>
=======
      <value>id(&quot;searchinput-61dee35cbd4b861dee35cb52f62&quot;)</value>
>>>>>>> Stashed changes
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
<<<<<<< Updated upstream
      <value>//input[@id='searchinput-61dea30e4119b61dea30e32da15']</value>
=======
      <value>//input[@id='searchinput-61dee35cbd4b861dee35cb52f62']</value>
>>>>>>> Stashed changes
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='region-main']/div/div/div/form/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
   </webElementXpaths>
</WebElementEntity>
